apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:xtVtzygIdTVuG1IhcOD+AlZIKJ/TqxY=,iv:LGX3d/7Cz395HkmZhuuQsLJvKmTZVpR3jMlWT948OYw=,tag:nIkvfgziZanJXZ9F8/Zg5Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:IhKxXox7Hax3mB3lBoljUZ/ju/Jm9GjNqHYrIIcB+kcZ/VSjTg==,iv:pb4x5bY0cOWSqaEVHCaK8o3BhbmsAVxSK3OOBPGZuXc=,tag:0yzw8gGfUj8Q0gMkjhgggQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:isV2fBsdLx/+OiMbpq9J2FOfu7KE,iv:iDPPomlC3dGNGMfzlhgXCphOfQINGbO9f1yOlJdkPr4=,tag:n/vUP4TxEIJ06PsGyCoBgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgrxvhm66pzd8pxldmgazldv28xk97m0239jqals4zpchtcx3adquaedzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUDRHdTk0R2dYSVJjR0R4
            MDJ3ZGxGNzZId3laRERucFRxK3VPNVVpRDBZCm1VdDBqZkErYkVOZzhnNkxpcTFB
            bFViekdpKzgxYUhLb0lrS2dUV1V5L2MKLS0tIGllbVIxdXhJMGY0MlB4QSthOERD
            RkphWkdTRlVWZ3h5RmdJRjgxOGtwdWsKTYouV3R1L7xNzSR4rOJVMS4CcslTOb70
            PANum1UJTx3H9J8FQyVMZofZMOgI043mtenthr+Ol1BTntuhEo8ghQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T01:29:57Z"
    mac: ENC[AES256_GCM,data:j71D/5h+Qy0VB8QcBsNKK7YjBSCSEd/X6NIpVB/qqjQaSuaRAUh0MwwwPe/eJ6sqtWvltYHQ0Cg1q8XXP1nHKkceHngq57S4VfcA/kShlhnc0sGz79jPwMwqa8dxak7JWvAGZJo4fanMTICS+O76SyIUyALOyGW5x7Q1feFtms0=,iv:pbY1MIKjLKYIyBsQcR1vRGKBprSIQdH/HFAAa5M8EKU=,tag:4nGi9czckm6iAYJgUu3XAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
