apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Y0pvPkLjloyl9rPCAnoKOp0cBEdMb4a0j6lpRp7yGiBvKjDSjjyv/A==,iv:569nTjChbxqL7D/TCUeqAm1y/PDd1xuuFEu1H3chve0=,tag:9D7OYu7OX27dg8ZeoyxKxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgrxvhm66pzd8pxldmgazldv28xk97m0239jqals4zpchtcx3adquaedzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZzkzQVpkR3ovdXFHQVdJ
            L01qNWxPSmhsOXExVVRWV1pBdnlISzBYNlJ3ClpaTjRDZWV0ck94alhwdlBSOFlB
            SHpIWGZmSytYNGRTOW1rcUdOWjE0YUkKLS0tIGFtTlltd21wVHZhN0tFVHdGaE5Z
            bWdOMTVYL0hpalBCdWNodTBXSWhRUkEKE8gsWFhJbSYMCcTTIrhrnDq2d4AbSrjU
            zAHQtAcMN0lAZGTaOOP2ueGXvz6tdIZ0HcE741kum7cU3bhqSI5A3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T01:29:57Z"
    mac: ENC[AES256_GCM,data:i8tBVyOFyhI7F1OvU+TG5P4c6Sopap1gK6SIyOEqFsfCERqacNpgfpfcJ4Sg8AnUVhHO7bi/dUW4iCplHfTk0YohaJxVic1t70TUFz8qXF6tZDnlycsfdp92Q9jXmXHSDpEkQR8CDCYHEUj4nAVgIkXBk357dpxTxwbBs+64rOs=,iv:ZEf4+cG1hNBnJW/fd8xGy6NWVL8nWwXdDg/6esSxrVE=,tag:GWX846MU5kSv5dgm4fLlWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
