---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "192.168.50.40"
  METALLB_LB_RANGE: "192.168.50.230-192.168.50.250"
  METALLB_K8S_GATEWAY_ADDR: "192.168.50.230"
  METALLB_INGRESS_ADDR: "192.168.50.250"
