apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cEh10AIs46XpHLNd0veAhw==,iv:GtiTEGdThUYE7IOHlql0WBc9SE5IKYKR2e9oTnvsle4=,tag:Pd7D5jI5hRKNwVafYbFG1g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:t0ziolmrUU3sdqZ3vF+lAODj/SMB/Uk=,iv:SJr2RHYqRNGEho3v4mCj8QTaj1qSeJp/9a4qpN9bqxk=,tag:Ii3sxLQSNn7hYzSksSl6tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgrxvhm66pzd8pxldmgazldv28xk97m0239jqals4zpchtcx3adquaedzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRllYUGlBZ08xQnFQM0h2
            ZGtHclBYcUZiWW5HNVZYd3lXVzJjU3BsblR3ClJXUys1SmF4ZUVadndQRHp6RFMx
            VTR3TDE2TVhITExIbzlhbHBqbjBUT3MKLS0tIE9xbjRBNURLUCtlUElFU05LMUF0
            Y0N0U05XOUF4QmsxbHAwOFB2SERRR00K/1+qm+RWxuRcAJaxdfYxR0ZuVejKUoPn
            BOrb1ul/UszsilMJyTSsTYj0LaRSQTQW+xK4nBXfiaro2xe09MZsZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T01:29:57Z"
    mac: ENC[AES256_GCM,data:Tjn4iPhnjIJIvqlLBl0WI3BWt59O/1CaDQyI+hxGMZAZ+/0irXvRJpM49Lyq+dHhAbFvS11M5GpIL7Y/tVtmVsJq1yeNk+hHjV5ktM1UJ1HpZWbzFdZwAYQBPVItsR2rwA+dJUD4EzabW4ME+VUcwZ4nVBfsozyl5DqPgKvXoHk=,iv:tAnYziQawKWS5RRLJGVXR1+2FOVveyTIJ/sY56BDqmU=,tag:GE6G/1SQ8/fHxvXY3D5TAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
